import store from "@/store";

export default [
    {
        path: "admins",
        name: "AdminadminsList",
        component: () => import("@/views/admins/list"),
        meta: { title: "管理员列表", authLogin: true },
    },
    {
        path: "adminsadd",
        name: "AdminadminsAdd",
        component: () => import("@/views/admins/add"),
        meta: { title: "添加管理员", authLogin: true },
    },
    {
        path: "adminsupdt",
        name: "AdminadminsUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "adminsupdtself",
        name: "AdminadminsUpdtSelf",
        props: (route) => ({ id: store.state.user.session.id }),
        component: () => import("@/views/admins/updt"),
        meta: { title: "编辑管理员", authLogin: true },
    },
    {
        path: "gongyingshang",
        name: "AdmingongyingshangList",
        component: () => import("@/views/gongyingshang/list"),
        meta: { title: "供应商列表", authLogin: true },
    },
    {
        path: "gongyingshangadd",
        name: "AdmingongyingshangAdd",
        component: () => import("@/views/gongyingshang/add"),
        meta: { title: "添加供应商", authLogin: true },
    },
    {
        path: "gongyingshangupdt",
        name: "AdmingongyingshangUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/gongyingshang/updt"),
        meta: { title: "编辑供应商", authLogin: true },
    },
    {
        path: "gongyingshangdetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdmingongyingshangDetail",
        component: () => import("@/views/gongyingshang/detail"),
        meta: { title: "供应商详情", authLogin: true },
    },
    {
        path: "shangpinfenlei",
        name: "AdminshangpinfenleiList",
        component: () => import("@/views/shangpinfenlei/list"),
        meta: { title: "商品分类列表", authLogin: true },
    },
    {
        path: "shangpinfenleiadd",
        name: "AdminshangpinfenleiAdd",
        component: () => import("@/views/shangpinfenlei/add"),
        meta: { title: "添加商品分类", authLogin: true },
    },
    {
        path: "shangpinfenleiupdt",
        name: "AdminshangpinfenleiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/shangpinfenlei/updt"),
        meta: { title: "编辑商品分类", authLogin: true },
    },
    {
        path: "shangpinxinxi",
        name: "AdminshangpinxinxiList",
        component: () => import("@/views/shangpinxinxi/list"),
        meta: { title: "商品信息列表", authLogin: true },
    },
    {
        path: "shangpinxinxiadd",
        name: "AdminshangpinxinxiAdd",
        component: () => import("@/views/shangpinxinxi/add"),
        meta: { title: "添加商品信息", authLogin: true },
    },
    {
        path: "shangpinxinxiupdt",
        name: "AdminshangpinxinxiUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/shangpinxinxi/updt"),
        meta: { title: "编辑商品信息", authLogin: true },
    },
    {
        path: "shangpinxinxidetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminshangpinxinxiDetail",
        component: () => import("@/views/shangpinxinxi/detail"),
        meta: { title: "商品信息详情", authLogin: true },
    },
    {
        path: "jinhuo",
        name: "AdminjinhuoList",
        component: () => import("@/views/jinhuo/list"),
        meta: { title: "进货列表", authLogin: true },
    },
    {
        path: "jinhuo_caozuoren",
        name: "AdminjinhuoListcaozuoren",
        component: () => import("@/views/jinhuo/list-caozuoren"),
        meta: { title: "进货列表", authLogin: true },
    },
    {
        path: "jinhuoadd",
        name: "AdminjinhuoAdd",
        component: () => import("@/views/jinhuo/add"),
        meta: { title: "添加进货", authLogin: true },
    },
    {
        path: "jinhuoupdt",
        name: "AdminjinhuoUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/jinhuo/updt"),
        meta: { title: "编辑进货", authLogin: true },
    },
    {
        path: "jinhuodetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminjinhuoDetail",
        component: () => import("@/views/jinhuo/detail"),
        meta: { title: "进货详情", authLogin: true },
    },
    {
        path: "xiaoshou",
        name: "AdminxiaoshouList",
        component: () => import("@/views/xiaoshou/list"),
        meta: { title: "销售列表", authLogin: true },
    },
    {
        path: "xiaoshou_caozuoren",
        name: "AdminxiaoshouListcaozuoren",
        component: () => import("@/views/xiaoshou/list-caozuoren"),
        meta: { title: "销售列表", authLogin: true },
    },
    {
        path: "xiaoshouadd",
        name: "AdminxiaoshouAdd",
        component: () => import("@/views/xiaoshou/add"),
        meta: { title: "添加销售", authLogin: true },
    },
    {
        path: "xiaoshouupdt",
        name: "AdminxiaoshouUpdt",
        props: (route) => ({ id: route.query.id }),
        component: () => import("@/views/xiaoshou/updt"),
        meta: { title: "编辑销售", authLogin: true },
    },
    {
        path: "xiaoshoudetail",
        props: (route) => ({ id: route.query.id }),
        name: "AdminxiaoshouDetail",
        component: () => import("@/views/xiaoshou/detail"),
        meta: { title: "销售详情", authLogin: true },
    },
];
